# Generated by Django 4.0.6 on 2022-07-23 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_alter_review_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='children_review', to='review.review'),
            preserve_default=False,
        ),
    ]
