# Generated by Django 4.0.6 on 2022-07-23 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_remove_review_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
    ]
