# Generated by Django 4.0.6 on 2022-07-23 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_developer_group_user_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('review', '0005_alter_review_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='dev',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_dev', to='users.developer'),
        ),
        migrations.AlterField(
            model_name='review',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owner_review', to=settings.AUTH_USER_MODEL),
        ),
    ]
