# Generated by Django 4.0.6 on 2022-07-23 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_developer_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='direction',
            field=models.ManyToManyField(blank=True, related_name='dev_direction', to='users.direction'),
        ),
    ]
