# Generated by Django 4.0.6 on 2022-07-23 03:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_developer_direction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='language',
        ),
        migrations.AlterField(
            model_name='client',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='developer',
            name='direction',
            field=models.ManyToManyField(blank=True, null=True, related_name='dev_direction', to='users.direction'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_developer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='direction',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='users.direction'),
        ),
    ]
